/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProducerRouteImport } from './routes/producer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ProducerUploadRouteImport } from './routes/producer.upload'
import { Route as ProducerSettingsRouteImport } from './routes/producer.settings'
import { Route as ProducerProfileRouteImport } from './routes/producer.profile'
import { Route as ProducerProductsRouteImport } from './routes/producer.products'
import { Route as ProducerOrdersRouteImport } from './routes/producer.orders'
import { Route as ProducerNotificationsRouteImport } from './routes/producer.notifications'
import { Route as ProducerEarningsRouteImport } from './routes/producer.earnings'
import { Route as ProducerDashboardRouteImport } from './routes/producer.dashboard'
import { Route as ProducerAnalyticsRouteImport } from './routes/producer.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as CustomerSettingsRouteImport } from './routes/customer.settings'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProducersRouteImport } from './routes/admin.producers'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ProducerProductsIdRouteImport } from './routes/producer.products.$id'
import { Route as CustomerRequestsIdRouteImport } from './routes/customer.requests.$id'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders.$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminNotificationsIdRouteImport } from './routes/admin.notifications.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerRoute = ProducerRouteImport.update({
  id: '/producer',
  path: '/producer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerUploadRoute = ProducerUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerSettingsRoute = ProducerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerProfileRoute = ProducerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerProductsRoute = ProducerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerOrdersRoute = ProducerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerNotificationsRoute = ProducerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerEarningsRoute = ProducerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerDashboardRoute = ProducerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProducerRoute,
} as any)
const ProducerAnalyticsRoute = ProducerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProducerRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/customer/wishlist',
  path: '/customer/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/customer/settings',
  path: '/customer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/customer/requests',
  path: '/customer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducersRoute = AdminProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ProducerProductsIdRoute = ProducerProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProducerProductsRoute,
} as any)
const CustomerRequestsIdRoute = CustomerRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRequestsRoute,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerOrdersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminNotificationsIdRoute = AdminNotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNotificationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/producer': typeof ProducerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/producers': typeof AdminProducersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/producer/analytics': typeof ProducerAnalyticsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/earnings': typeof ProducerEarningsRoute
  '/producer/notifications': typeof ProducerNotificationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/producer/products': typeof ProducerProductsRouteWithChildren
  '/producer/profile': typeof ProducerProfileRoute
  '/producer/settings': typeof ProducerSettingsRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/producer/products/$id': typeof ProducerProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/producer': typeof ProducerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/producers': typeof AdminProducersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/producer/analytics': typeof ProducerAnalyticsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/earnings': typeof ProducerEarningsRoute
  '/producer/notifications': typeof ProducerNotificationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/producer/products': typeof ProducerProductsRouteWithChildren
  '/producer/profile': typeof ProducerProfileRoute
  '/producer/settings': typeof ProducerSettingsRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/producer/products/$id': typeof ProducerProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/producer': typeof ProducerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/producers': typeof AdminProducersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/requests': typeof CustomerRequestsRouteWithChildren
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/producer/analytics': typeof ProducerAnalyticsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/earnings': typeof ProducerEarningsRoute
  '/producer/notifications': typeof ProducerNotificationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/producer/products': typeof ProducerProductsRouteWithChildren
  '/producer/profile': typeof ProducerProfileRoute
  '/producer/settings': typeof ProducerSettingsRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/notifications/$id': typeof AdminNotificationsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/requests/$id': typeof CustomerRequestsIdRoute
  '/producer/products/$id': typeof ProducerProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/custom'
    | '/forgot-password'
    | '/login'
    | '/producer'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/producers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/requests'
    | '/customer/settings'
    | '/customer/wishlist'
    | '/dashboard/admin'
    | '/producer/analytics'
    | '/producer/dashboard'
    | '/producer/earnings'
    | '/producer/notifications'
    | '/producer/orders'
    | '/producer/products'
    | '/producer/profile'
    | '/producer/settings'
    | '/producer/upload'
    | '/product/$id'
    | '/admin/'
    | '/admin/notifications/$id'
    | '/admin/users/$id'
    | '/customer/orders/$id'
    | '/customer/requests/$id'
    | '/producer/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/custom'
    | '/forgot-password'
    | '/login'
    | '/producer'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/producers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/requests'
    | '/customer/settings'
    | '/customer/wishlist'
    | '/dashboard/admin'
    | '/producer/analytics'
    | '/producer/dashboard'
    | '/producer/earnings'
    | '/producer/notifications'
    | '/producer/orders'
    | '/producer/products'
    | '/producer/profile'
    | '/producer/settings'
    | '/producer/upload'
    | '/product/$id'
    | '/admin'
    | '/admin/notifications/$id'
    | '/admin/users/$id'
    | '/customer/orders/$id'
    | '/customer/requests/$id'
    | '/producer/products/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/custom'
    | '/forgot-password'
    | '/login'
    | '/producer'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/producers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/requests'
    | '/customer/settings'
    | '/customer/wishlist'
    | '/dashboard/admin'
    | '/producer/analytics'
    | '/producer/dashboard'
    | '/producer/earnings'
    | '/producer/notifications'
    | '/producer/orders'
    | '/producer/products'
    | '/producer/profile'
    | '/producer/settings'
    | '/producer/upload'
    | '/product/$id'
    | '/admin/'
    | '/admin/notifications/$id'
    | '/admin/users/$id'
    | '/customer/orders/$id'
    | '/customer/requests/$id'
    | '/producer/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CustomRoute: typeof CustomRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProducerRoute: typeof ProducerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOrdersRoute: typeof CustomerOrdersRouteWithChildren
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerRequestsRoute: typeof CustomerRequestsRouteWithChildren
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer': {
      id: '/producer'
      path: '/producer'
      fullPath: '/producer'
      preLoaderRoute: typeof ProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/upload': {
      id: '/producer/upload'
      path: '/upload'
      fullPath: '/producer/upload'
      preLoaderRoute: typeof ProducerUploadRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/settings': {
      id: '/producer/settings'
      path: '/settings'
      fullPath: '/producer/settings'
      preLoaderRoute: typeof ProducerSettingsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/profile': {
      id: '/producer/profile'
      path: '/profile'
      fullPath: '/producer/profile'
      preLoaderRoute: typeof ProducerProfileRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/products': {
      id: '/producer/products'
      path: '/products'
      fullPath: '/producer/products'
      preLoaderRoute: typeof ProducerProductsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/orders': {
      id: '/producer/orders'
      path: '/orders'
      fullPath: '/producer/orders'
      preLoaderRoute: typeof ProducerOrdersRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/notifications': {
      id: '/producer/notifications'
      path: '/notifications'
      fullPath: '/producer/notifications'
      preLoaderRoute: typeof ProducerNotificationsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/earnings': {
      id: '/producer/earnings'
      path: '/earnings'
      fullPath: '/producer/earnings'
      preLoaderRoute: typeof ProducerEarningsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/dashboard': {
      id: '/producer/dashboard'
      path: '/dashboard'
      fullPath: '/producer/dashboard'
      preLoaderRoute: typeof ProducerDashboardRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/producer/analytics': {
      id: '/producer/analytics'
      path: '/analytics'
      fullPath: '/producer/analytics'
      preLoaderRoute: typeof ProducerAnalyticsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/customer/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/customer/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/customer/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producers': {
      id: '/admin/producers'
      path: '/producers'
      fullPath: '/admin/producers'
      preLoaderRoute: typeof AdminProducersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producer/products/$id': {
      id: '/producer/products/$id'
      path: '/$id'
      fullPath: '/producer/products/$id'
      preLoaderRoute: typeof ProducerProductsIdRouteImport
      parentRoute: typeof ProducerProductsRoute
    }
    '/customer/requests/$id': {
      id: '/customer/requests/$id'
      path: '/$id'
      fullPath: '/customer/requests/$id'
      preLoaderRoute: typeof CustomerRequestsIdRouteImport
      parentRoute: typeof CustomerRequestsRoute
    }
    '/customer/orders/$id': {
      id: '/customer/orders/$id'
      path: '/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof CustomerOrdersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/notifications/$id': {
      id: '/admin/notifications/$id'
      path: '/$id'
      fullPath: '/admin/notifications/$id'
      preLoaderRoute: typeof AdminNotificationsIdRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
  }
}

interface AdminNotificationsRouteChildren {
  AdminNotificationsIdRoute: typeof AdminNotificationsIdRoute
}

const AdminNotificationsRouteChildren: AdminNotificationsRouteChildren = {
  AdminNotificationsIdRoute: AdminNotificationsIdRoute,
}

const AdminNotificationsRouteWithChildren =
  AdminNotificationsRoute._addFileChildren(AdminNotificationsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProducersRoute: typeof AdminProducersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProducersRoute: AdminProducersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProducerProductsRouteChildren {
  ProducerProductsIdRoute: typeof ProducerProductsIdRoute
}

const ProducerProductsRouteChildren: ProducerProductsRouteChildren = {
  ProducerProductsIdRoute: ProducerProductsIdRoute,
}

const ProducerProductsRouteWithChildren =
  ProducerProductsRoute._addFileChildren(ProducerProductsRouteChildren)

interface ProducerRouteChildren {
  ProducerAnalyticsRoute: typeof ProducerAnalyticsRoute
  ProducerDashboardRoute: typeof ProducerDashboardRoute
  ProducerEarningsRoute: typeof ProducerEarningsRoute
  ProducerNotificationsRoute: typeof ProducerNotificationsRoute
  ProducerOrdersRoute: typeof ProducerOrdersRoute
  ProducerProductsRoute: typeof ProducerProductsRouteWithChildren
  ProducerProfileRoute: typeof ProducerProfileRoute
  ProducerSettingsRoute: typeof ProducerSettingsRoute
  ProducerUploadRoute: typeof ProducerUploadRoute
}

const ProducerRouteChildren: ProducerRouteChildren = {
  ProducerAnalyticsRoute: ProducerAnalyticsRoute,
  ProducerDashboardRoute: ProducerDashboardRoute,
  ProducerEarningsRoute: ProducerEarningsRoute,
  ProducerNotificationsRoute: ProducerNotificationsRoute,
  ProducerOrdersRoute: ProducerOrdersRoute,
  ProducerProductsRoute: ProducerProductsRouteWithChildren,
  ProducerProfileRoute: ProducerProfileRoute,
  ProducerSettingsRoute: ProducerSettingsRoute,
  ProducerUploadRoute: ProducerUploadRoute,
}

const ProducerRouteWithChildren = ProducerRoute._addFileChildren(
  ProducerRouteChildren,
)

interface CustomerOrdersRouteChildren {
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
}

const CustomerOrdersRouteChildren: CustomerOrdersRouteChildren = {
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
}

const CustomerOrdersRouteWithChildren = CustomerOrdersRoute._addFileChildren(
  CustomerOrdersRouteChildren,
)

interface CustomerRequestsRouteChildren {
  CustomerRequestsIdRoute: typeof CustomerRequestsIdRoute
}

const CustomerRequestsRouteChildren: CustomerRequestsRouteChildren = {
  CustomerRequestsIdRoute: CustomerRequestsIdRoute,
}

const CustomerRequestsRouteWithChildren =
  CustomerRequestsRoute._addFileChildren(CustomerRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CustomRoute: CustomRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProducerRoute: ProducerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOrdersRoute: CustomerOrdersRouteWithChildren,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerRequestsRoute: CustomerRequestsRouteWithChildren,
  CustomerSettingsRoute: CustomerSettingsRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
